language: java
jdk:
  - oraclejdk8
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
script: mvn test
before_deploy:
  - mvn package -DskipTests=true
deploy:
  skip_cleanup: true
  provider: script
  script: mvn -s .travis-maven-settings.xml release:prepare -B && mvn -s .travis-maven-settings.xml release:perform
  on:
    branch: master
    tags: true
