language: java
jdk:
  - oraclejdk8
script: mvn test
before_deploy:
  - git checkout master
  - mvn package -DskipTests=true
  - openssl aes-256-cbc -K $encrypted_7c93ac5960c4_key -iv $encrypted_7c93ac5960c4_iv
    -in .travis/keys/github_deploy.enc
    -out ~/.ssh/github_deploy -d
  - cp .travis/keys/github_deploy.pub ~/.ssh/
deploy:
  skip_cleanup: true
  provider: script
  script:
    - mvn -s .travis-maven-settings.xml -B -X release:prepare
    - mvn -s .travis-maven-settings.xml -X release:perform
  on:
    branch: master
